services:
  front:
    container_name: nnp-stream-front
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    restart: unless-stopped
    env_file:
      - .env
    # expose:
    #   - "${PORT}"
    ports:
      - "${PORT}:${PORT}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'node -e "require(''http'').get(''http://localhost:3000'', r => process.exit(r.statusCode === 200 ? 0 : 1)).on(''error'', () => process.exit(1))"',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
